global using BuildingBlocks.CQRS;
global using BuildingBlocks.Interfaces;
global using FluentValidation;
global using Magic.Application.Dtos;
global using Magic.Application.Dtos.Common;
global using Magic.Application.Extensions;
global using Magic.Domain.Models;
global using Magic.Domain.Models.Lookups;
global using Magic.Application.Exceptions;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using DomainEnums = Magic.Domain.Enums;
global using Magic.Application.Common.Interfaces;
global using Magic.Application.Dtos.Identity;
global using Microsoft.AspNetCore.Identity;
global using BuildingBlocks.Models;
global using Magic.Domain.Specifications;