// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Provider.Infrastructure.Data;

#nullable disable

namespace Provider.Infrastructure.Migrations
{
    [DbContext(typeof(ProviderDbContext))]
    [Migration("20250728104242_newzeft")]
    partial class newzeft
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Provider.Domain.Models.DamenAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CalculateFee")
                        .HasColumnType("bit");

                    b.Property<bool>("Credit")
                        .HasColumnType("bit");

                    b.Property<int>("DamenServiceId")
                        .HasColumnType("int");

                    b.Property<string>("EnLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUserEntered")
                        .HasColumnType("bit");

                    b.Property<decimal?>("RangeMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RangeMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Replace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DamenServiceId")
                        .IsUnique();

                    b.ToTable("DamenAmount");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DamenServices");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DamenServiceId")
                        .HasColumnType("int");

                    b.Property<string>("EnLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DamenServiceId")
                        .IsUnique();

                    b.ToTable("DamenServiceCharges");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceChargeSlide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DamenServiceChargeId")
                        .HasColumnType("int");

                    b.Property<decimal>("FromValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ScValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScValueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ToValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DamenServiceChargeId");

                    b.ToTable("DamenServiceChargeSlide");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<int>("DamenServiceId")
                        .HasColumnType("int");

                    b.Property<string>("DefaultVal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPassword")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxLen")
                        .HasColumnType("int");

                    b.Property<int?>("MinLen")
                        .HasColumnType("int");

                    b.Property<bool?>("Required")
                        .HasColumnType("bit");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DamenServiceId");

                    b.ToTable("DamenServiceFields");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DamenServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DamenServiceId");

                    b.ToTable("DamenServiceRequests");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceRequestInputField", b =>
                {
                    b.Property<int>("DamenServiceRequestId")
                        .HasColumnType("int");

                    b.Property<int>("DataFieldId")
                        .HasColumnType("int");

                    b.HasKey("DamenServiceRequestId", "DataFieldId");

                    b.HasIndex("DataFieldId");

                    b.ToTable("DamenServiceRequestInputField");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceRequestOutputField", b =>
                {
                    b.Property<int>("DamenServiceRequestId")
                        .HasColumnType("int");

                    b.Property<int>("DataFieldId")
                        .HasColumnType("int");

                    b.HasKey("DamenServiceRequestId", "DataFieldId");

                    b.HasIndex("DataFieldId");

                    b.ToTable("DamenServiceRequestOutputField");
                });

            modelBuilder.Entity("Provider.Domain.Models.FawryBiller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSupportOverPay")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSupportPartialPay")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FawryBillers");
                });

            modelBuilder.Entity("Provider.Domain.Models.FawryBillerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BillerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PmtType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SupportInquiry")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportOverPay")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportPartialPay")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportReversal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BillerId");

                    b.ToTable("FawryBillerInfos");
                });

            modelBuilder.Entity("Provider.Domain.Models.FawryPaymentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillerInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillerInfoId");

                    b.ToTable("FawryPaymentItems");
                });

            modelBuilder.Entity("Provider.Domain.Models.FawryServiceCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillerInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillerInfoId");

                    b.ToTable("ServiceCharge");
                });

            modelBuilder.Entity("Provider.Domain.Models.FawryServiceChargeTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Charge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("From")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceChargeId")
                        .HasColumnType("int");

                    b.Property<decimal>("To")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceChargeId");

                    b.ToTable("FawryServiceChargeTier");
                });

            modelBuilder.Entity("Provider.Domain.Models.MasaryService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("InquiryRequired")
                        .HasColumnType("bit");

                    b.Property<double>("MaxValue")
                        .HasColumnType("float");

                    b.Property<double>("MinValue")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MasaryService");
                });

            modelBuilder.Entity("Provider.Domain.Models.MasaryServiceCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Charge")
                        .HasColumnType("float");

                    b.Property<double>("From")
                        .HasColumnType("float");

                    b.Property<bool>("Percentage")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<double>("Slap")
                        .HasColumnType("float");

                    b.Property<double>("To")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("MasaryServiceCharge");
                });

            modelBuilder.Entity("Provider.Domain.Models.MasaryServiceParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ClientId")
                        .HasColumnType("bit");

                    b.Property<bool>("ConfirmRequired")
                        .HasColumnType("bit");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int>("MinLength")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("MasaryServiceParameter");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenAmount", b =>
                {
                    b.HasOne("Provider.Domain.Models.DamenService", "DamenService")
                        .WithOne("Amount")
                        .HasForeignKey("Provider.Domain.Models.DamenAmount", "DamenServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamenService");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceCharge", b =>
                {
                    b.HasOne("Provider.Domain.Models.DamenService", "DamenService")
                        .WithOne("ServiceCharge")
                        .HasForeignKey("Provider.Domain.Models.DamenServiceCharge", "DamenServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamenService");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceChargeSlide", b =>
                {
                    b.HasOne("Provider.Domain.Models.DamenServiceCharge", "DamenServiceCharge")
                        .WithMany("Slides")
                        .HasForeignKey("DamenServiceChargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamenServiceCharge");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceField", b =>
                {
                    b.HasOne("Provider.Domain.Models.DamenService", "DamenService")
                        .WithMany("DataFields")
                        .HasForeignKey("DamenServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamenService");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceRequest", b =>
                {
                    b.HasOne("Provider.Domain.Models.DamenService", "DamenService")
                        .WithMany("Requests")
                        .HasForeignKey("DamenServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamenService");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceRequestInputField", b =>
                {
                    b.HasOne("Provider.Domain.Models.DamenServiceRequest", "DamenServiceRequest")
                        .WithMany("Inputs")
                        .HasForeignKey("DamenServiceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Provider.Domain.Models.DamenServiceField", "DataField")
                        .WithMany()
                        .HasForeignKey("DataFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamenServiceRequest");

                    b.Navigation("DataField");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceRequestOutputField", b =>
                {
                    b.HasOne("Provider.Domain.Models.DamenServiceRequest", "DamenServiceRequest")
                        .WithMany("Outputs")
                        .HasForeignKey("DamenServiceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Provider.Domain.Models.DamenServiceField", "DataField")
                        .WithMany()
                        .HasForeignKey("DataFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamenServiceRequest");

                    b.Navigation("DataField");
                });

            modelBuilder.Entity("Provider.Domain.Models.FawryBillerInfo", b =>
                {
                    b.HasOne("Provider.Domain.Models.FawryBiller", "Biller")
                        .WithMany("BillerInfos")
                        .HasForeignKey("BillerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biller");
                });

            modelBuilder.Entity("Provider.Domain.Models.FawryPaymentItem", b =>
                {
                    b.HasOne("Provider.Domain.Models.FawryBillerInfo", "BillerInfo")
                        .WithMany("PaymentItems")
                        .HasForeignKey("BillerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillerInfo");
                });

            modelBuilder.Entity("Provider.Domain.Models.FawryServiceCharge", b =>
                {
                    b.HasOne("Provider.Domain.Models.FawryBillerInfo", "BillerInfo")
                        .WithMany("Fees")
                        .HasForeignKey("BillerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillerInfo");
                });

            modelBuilder.Entity("Provider.Domain.Models.FawryServiceChargeTier", b =>
                {
                    b.HasOne("Provider.Domain.Models.FawryServiceCharge", "ServiceCharge")
                        .WithMany("FeesTiers")
                        .HasForeignKey("ServiceChargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceCharge");
                });

            modelBuilder.Entity("Provider.Domain.Models.MasaryServiceCharge", b =>
                {
                    b.HasOne("Provider.Domain.Models.MasaryService", "MasaryServiceslist")
                        .WithMany("ServiceCharges")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasaryServiceslist");
                });

            modelBuilder.Entity("Provider.Domain.Models.MasaryServiceParameter", b =>
                {
                    b.HasOne("Provider.Domain.Models.MasaryService", "MasaryServiceslist")
                        .WithMany("ServiceParameter")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasaryServiceslist");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenService", b =>
                {
                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("DataFields");

                    b.Navigation("Requests");

                    b.Navigation("ServiceCharge")
                        .IsRequired();
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceCharge", b =>
                {
                    b.Navigation("Slides");
                });

            modelBuilder.Entity("Provider.Domain.Models.DamenServiceRequest", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("Provider.Domain.Models.FawryBiller", b =>
                {
                    b.Navigation("BillerInfos");
                });

            modelBuilder.Entity("Provider.Domain.Models.FawryBillerInfo", b =>
                {
                    b.Navigation("Fees");

                    b.Navigation("PaymentItems");
                });

            modelBuilder.Entity("Provider.Domain.Models.FawryServiceCharge", b =>
                {
                    b.Navigation("FeesTiers");
                });

            modelBuilder.Entity("Provider.Domain.Models.MasaryService", b =>
                {
                    b.Navigation("ServiceCharges");

                    b.Navigation("ServiceParameter");
                });
#pragma warning restore 612, 618
        }
    }
}
