global using Magic.Infrastructure.Data;
global using Magic.Infrastructure.Data.Interceptors;
global using Microsoft.EntityFrameworkCore;
global using Magic.Domain.Models;
global using Magic.Domain.Models.Lookups;
global using Magic.Domain.Abstractions;
global using System.Text.Json;
global using Magic.Application.Dtos.Common;
global using Magic.Application.Common.Interfaces;
global using DomainEnums = Magic.Domain.Enums;
global using Magic.Application.Common;
