global using Magic.Application.Common;
global using Magic.Application.Common.Interfaces;
global using Magic.Domain.Abstractions;
global using Magic.Domain.Models;
global using Magic.Domain.Models.Lookups;
global using Magic.Infrastructure.Data;
global using Magic.Infrastructure.Data.Interceptors;
global using Microsoft.EntityFrameworkCore;
global using CommonEnums = BuildingBlocks.Enums;
global using DomainEnums = Magic.Domain.Enums;
global using Lookups = Magic.Domain.Models.Lookups;
global using Magic.Application.Common.Configurations;
global using BuildingBlocks.Extensions;
